services:
  vpn-server:
    image: strongx509/strongswan:latest
    container_name: vpn-server
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./server:/etc/swanctl
      - ./strongswan.conf:/etc/strongswan.conf
    networks:
      vpn-net:
        ipv4_address: 10.0.0.2

  vpn-client:
    image: strongx509/strongswan:latest
    container_name: vpn-client
    depends_on:
      - vpn-server
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./client:/etc/swanctl
      - ./strongswan.conf:/etc/strongswan.conf
    networks:
      vpn-net:
        ipv4_address: 10.0.0.3

networks:
  vpn-net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
